name: advent_of_code
description: A new Flutter application.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
